services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"

  app:
    container_name: keycloak-sso-app
    build: ./web-app
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
