services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev --import-realm --proxy=edge --https-certificate-file=/certs/cert.pem --https-certificate-key-file=/certs/key.pe
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ../certs:/certs
    expose:
      - "8443"

  app:
    container_name: keycloak-sso-app
    build: ./web-app
    expose:
      - "3000"
    depends_on:
      - keycloak
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      NODE_ENV: development

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - keycloak
      - app
